name: CI/CD

on:
  pull_request:
    branches: [ "dev", "main" ]
  push:
    branches: [ "dev", "main" ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      # Setup Rust stable using dtolnay/rust-toolchain
      - name: Setup Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
          targets: x86_64-unknown-linux-gnu

      # Cache Cargo + Rustup
      - name: Cache Cargo and Rustup
        uses: Swatinem/rust-cache@v2

      - name: Run Clippy (Lint)
        run: cargo clippy --all-targets --all-features -- -D warnings

  # -------------
  # 3) Run Tests
  # -------------
  test:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      # Setup Rust stable again for test job
      - name: Setup Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu

      # Cache Cargo + Rustup
      - name: Cache Cargo and Rustup
        uses: Swatinem/rust-cache@v2

      - name: Run Tests
        run: cargo test --verbose